{{- if .Values.clusterRole.create  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vantage-kubernetes-agent.fullname" . }}
  labels:
    {{- include "vantage-kubernetes-agent.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["nodes/metrics"]
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - "nodes"
  - "pods"
  - "namespaces"
  - "replicationcontrollers"
  - "persistentvolumes"
  - "persistentvolumeclaims"
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources:
  - "replicasets"
  - "deployments"
  - "statefulsets"
  - "daemonsets"
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources:
  - "jobs"
  - "cronjobs"
  verbs: ["get", "watch", "list"]
{{- if .Values.agent.gpu.usageMetrics}}
- apiGroups: [""]
  resources:
  - "endpoints"
  verbs: ["get", "watch", "list"]
{{- end}}
{{- if .Values.agent.argocdRollouts}}
- apiGroups: ["argoproj.io"]
  resources:
  - "rollouts"
  verbs: ["get", "watch", "list"]
{{- end}}
{{- end}}
